name: Release

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup Node.js 16
        uses: actions/setup-node@master
        with:
          node-version: '>=16.x'
      - name: Install Dependencies
        run: yarn install
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @takeda-digital:registry=https://takedaazuseast.jfrog.io/artifactory/api/npm/exp-npm-local/
            //takedaazuseast.jfrog.io/artifactory/api/npm/exp-npm-local/:_auth=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          publish: yarn release
          commit: Version release
          title: Next release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
      - name: Create PR to develop if a publish happens
        if: steps.changesets.outputs.published == 'true'
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ github.event.repository.default_branch }}
          github_token: ${{ secrets.MY_GITHUB_PAT }}
